name: Xcode - Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: xcodebuild clean build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO

      - name: Clean 
        run: cp -v build/Release/*.app .
